### ISSUE TITLE
Doesn't build with dmd 2.078 (AA key type doesn't have opEquals)

### ISSUE THREAD

**Issue by SimonN** [SimonN/LixD#282]
Lix 0.9.7 and many earlier versions too.

```
$ dub -f
Performing "debug" build using /usr/bin/dmd for x86_64.
allegro 4.0.1+5.2.0: building configuration "no-libs"...
derelict-util 2.1.0: building configuration "library"...
derelict-enet 2.0.0: building configuration "library"...
enumap 0.4.1: building configuration "library"...
lix 0.9.7+commit.4.g799d2c56: building configuration "application"...
Compiling Lix 0.9.7...
src/tile/tilelib.d(97,25): Error: AA key type TileGroupKey does not have 'bool opEquals(ref const TileGroupKey) const'
/usr/bin/dmd failed with exit code 1.

$ dmd --version
DMD64 D Compiler v2.078.0
Copyright (c) 1999-2017 by The D Language Foundation written by Walter Bright
```
