### ISSUE TITLE
Won't compile with dmd 2.077

### ISSUE THREAD

**Issue by SimonN** [SimonN/LixD#259]
Update to dmd 2.077 from 2017-11-03. This will happen when you compile Lix:
```
Compiling Lix 0.9.2...
/usr/include/dlang/dmd/std/conv.d(4502,34): Deprecation: lix.job.Job.lixxie is not visible from module std.conv
/usr/include/dlang/dmd/std/conv.d(4502,34): Error: class lix.skill.leaver.RemovedLix member lixxie is not accessible
/usr/include/dlang/dmd/std/conv.d(4604,21): Error: template instance std.conv.emplace!(RemovedLix) error instantiating
src/lix/job.d(112,51):        instantiated from here: emplace!(RemovedLix)
/usr/include/dlang/dmd/std/conv.d(4502,34): Deprecation: lix.job.Job.lixxie is not visible from module std.conv
/usr/include/dlang/dmd/std/conv.d(4502,34): Error: class lix.skill.faller.Faller member lixxie is not accessible
/usr/include/dlang/dmd/std/conv.d(4604,21): Error: template instance std.conv.emplace!(Faller) error instantiating
src/lix/job.d(113,47):        instantiated from here: emplace!(Faller)
[...]
```

When you make `lixxie()` public, the game compiles, runs, starts levels, but crashes on spawning the first lix.
